# ------------------------
# Adopta Agency Blueprint
# This is meant to be a blueprint for opening up data.
# You control everything about this site, here in the _config.yml
# All data is stored under /data
# All API definitions are stored under /api
# Tell your story via the /blog
# Manage all conversations through this project's Github issues
# ------------------------

# Give your peject a title, description, some tags, and URL to Github home page
project_title: My Brother's Keeper
project_description: This project makes the data associated with President Obama's My Brother's Keeper initiative available in an open format.
project_url: http://audreywatters.github.io/mybrotherskeeper/
project_tags:
  - tag: race
  - tag: open data
  - tag: gender
  - tag: education

# ---------
# You can add a new tag for each tag associated with your project
# ---------  

github_user: audreywatters
github_repo: mybrotherskeeper

# ---------
# This is the section refers to the contents inside the data folder. Here is where you describe the data involved in your project. If you choose to show the data, it will list the contents of this folder on the index.html page. If you choose to turn the "nav" on (or off), it will display (or not) the link to the data on the lefthand navigation.
# ---------
data_show: yes
data_nav: yes
data_title: Data Files
data_description: This is just a sample set of dataset.
data_footer: The goal of publishing these CSV and JSON alternatives is to make this data easier for humans and machines to utilize.

# You can add one or many data sets here, with a title, and link to CSV and JSON file
data:
  - title: "Farmers Markets"
    csv_url: "http://adopta-agency.github.io/adopta-blueprint/data/farmers_markets.csv"
    json_url: "http://adopta-agency.github.io/adopta-blueprint/data/farmers_markets.json"

# ---------
# APIs
# You do not have to create an API for your dataset.
# ---------

api_show: no
api_nav: no
api_title: APIs
api_description: This is a sample API generated from the dataset above. It is described using Swagger which allows the generation of interactive documentation, while also describing the meta data and surface area of an API.
api_footer: The goal of launching these APIs is to make this data easier to consumer, and integrate into websites, applications, visualizations, and other integrations.

api:
  - title: 
    swagger_url: 

# ---------
# Showcase
# This section highlights projects that use the datasets you've cleaned up
# ---------

showcase_show: no
showcase_nav: no
showcase_title: Showcase
showcase_description: This is a showcase of what is being build on top of this open data and APIs. Right now it is just sample data, but when you launch for your project, you can showcase everything that is being developed.
showcase_footer: This project is designed to be used, and extended, please share what you have built so it can be included here on the showcase, for others to find.

showcase:
  - title: Showcase Item One
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com
  - title: Showcase Item Two
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com
  - title: Showcase Item Four
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com

# ---------
# FAQ
# Here you can offer Q&A with the datasets and the processes surrounding your particular dataset
# ---------

faq_show: yes
faq_nav: no
faq_title: FAQ
faq_description: These are some of the common questions that need answering, or get asked as part of the work around this project.
faq_footer: Questions that get submitted via the projects Github issue managment are sometimes added here.

faq:
  - question: Why are you doing this?
    answer: I want to make data more accessible and usable, encouraging people to build it into more websites, applications, visualizations, and anywhere it can be used.
  - question: Where did this data come from?
    answer: It could come from data.gov, one of the data.json files of government agencies, or any other location you find the data you need.
  - question: What are you planning on doing with this data?
    answer: You can visit the <a href="http://adopta-agency.github.io/adopta-blueprint/roadmap/">roadmap</a> for more information.
  - question: How do I talk to someone behind this project?
    answer: This site runs on Github Pages, and relies on Github issue management for support. <a href="https://github.com/audreywatters/adopta-blueprint/issues/new">Go ahead and submit an issue</a> via the project repository.

# ---------
# Team
# ---------

team_show: yes
team_nav: no
team_title: Team
team_description: This is a solo project conducted by Audrey Watters as part of <a href="http://kinlane.com">Kin Lane</a>'s Adopta.Agency project.
team_footer: If you would like to get involved with this work, please submit an issue via the Github repo.

team:
  - name: Audrey Watters
    description: Writer
    url: http://audreywatters.com

# ---------
# Tools
# If you are using a special tool, you can highlight it here. 
# ---------

tools_show: no
tools_nav: no
tools_title: Tools
tools_description: This is a list of tools that are used as part of this project.
tools_footer: We share the tools we used to help others understand how to recreate the work.

tools:
  - title: Github
    description: Social Project Platform
    url: http://github.com
  - title: Github Pages
    description: Free Project Hosting
    url: https://pages.github.com/
  - title: Google Spreadsheets
    description: Web-based Spreadsheets
    url: https://www.google.com/drive/
  - title: API Spark
    description: API Deployment From Spreadsheets.
    url: http://restlet.com/products/apispark/
  - title: CSV Converter
    description: CSV to JSON Converter
    url: http://adopta-agency.github.io/csv-converter/
  - title: JSON Editor Online
    description: JSON Editor
    url: http://www.jsoneditoronline.org/

# ---------
# Blog
# You don't have to create a blog for this project. But you can opt to create blog pages that serve as status updates on the project. To create a new blog post, make a copy of the original file inside the _posts folder. Rename it, adjusting the filename with the right data and title. Open that file to adjust the blog post title and contents.
# ---------

permalink: /:categories/:year/:month/:day/:title
paginate: 25
paginate_path: "/blog/page:num"
blog_nav: yes

# ---------
# Support
# If folks need help, who will they contact? (Go ahead. Leave API Evangelist as the contact person. I know I will.)
# ---------

# URL to the issues page for this
support_title: Support
support_description: If you need any help, have questions, or would like to get involved, please use the following links.
support_email: info@apievangelist.com
support_twitter: audreywatters

# ---------
# Roadmap
# ---------

roadmap_show: yes
roadmap_nav: yes

# ---------
# Change Log
# ---------

changelog_show: yes
changelog_nav: yes

# ---------
# General Settings
# ---------

#versioning your peojct is good
version:      1.1.1

#some configurations for the site
markdown:     rdiscount
permalink:    pretty
pygments:     true


#what files should be excluded
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
